export const CHAT_ADD_MESSAGE = 'CHAT_ADD_MESSAGE';
export const CHAT_FETCH_MESSAGES = 'CHAT_FETCH_MESSAGES';
export const CHAT_FETCHED_MESSAGES = 'CHAT_FETCHED_MESSAGES';
export const CHAT_UNSHIFT_MESSAGE = 'CHAT_UNSHIFT_MESSAGE';
export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE';
